### PR TITLE
refactor program/shader/DRY into separate Glsl.Program class

### PR DESCRIPTION
**Pull request by r3mi**
Hello,

very nice library and nice idea !
I would like to use it for some 2D image processing but I require a specific vertex shader (for some warping), and sometimes 2 fragment shaders (2 gl programs).
I refactored the glsl.js code to put program / shaders / DRY stuff into a separate Glsl.Program class, so that I can instantiate it directly (instead of Glsl) with a different vertex shader.
Code is otherwise unchanged.
If you think this could be compatible with what you want for glsl.js , here is my work.

### CODE REVIEW

**Comment by gre** [comment]
Sounds good to me.
Thanks for your contribution.

Cheers

**Comment by gre** [comment]
Can we expose the feature back to the options you give at the Glsl() instanciation now?

Like:

Glsl({
  fragment: "..."
  vertex: "..."
})

Do you have a use case? How can it works with multiple fragments ?

would this API works? :
Glsl({
  fragment: [ ".frag1..", "...frag2" ]
  vertex: "..."
})

Regards

**Comment by r3mi** [comment]
For the time being, I either use Glsl() for standard usage, or Glsl.Program() directly if I need the extra options.

For exposing 'vertex' in Glsl() : if you change the code of the default vertex shader because of specific needs, you might also have a specific geometry different from the default one (the 2 triangles covering the whole canvas), or specific textures. So you need to change render(), load() & syncResolution(). Might as well use Glsl.Program() directly. What do you think ?

For exposing multiple 'fragment' in Glsl() : could be useful, eg to apply multiple effects in 2D image processing. Will require creating multiple Glsl.Program and switching between them. Sometime might involve framebuffers and sometime not. Can it be done in a generic way ?

**Comment by N0NameN0** [comment]
I actually use "gre" version even for "multi shader", but you are right, it's pain in ass, to merge to a single shader code from several ;)

**Comment by gre** [comment]
Ok, I see what you mean, my only concerns is to not lose users of the lib when they will see 2 ways of doing the same thing.

In term of API I mean, I would like everything to be done with the Glsl({}).
Could we imagine to give the Program in argument and also a redefinition of everything needed (like load() render() ...) ?

**Comment by r3mi** [comment]
ah, compris.

so, starting with vertex shader: 
would need to provide in Glsl constructor:
- 'vertex' shader
- 'render' function
- a function to create array buffer(s) or element arrays or specific vertex attributes (middle part of load() currently). something like 'onLoad' ?
- a function to take resize into account (last line of syncResolution). something like 'onSetSize' ?
- all these options will have defaults : 'vertexDefault', 'renderDefault', ... ?
- there is also the UNPACK_FLIP_Y_WEBGL which might be needed or not, depending on the code of the vertex shader. add an option ?

**Comment by N0NameN0** [comment]
i finnaly get it working !! ;) thx R3mi.

**Pull request merged**
