### PR TITLE
Allow users to specify arguments to canvas.getContext()

### PR DESCRIPTION
**Pull request by k4b7**
Allow users to specify arguments to canvas.getContext().  Arguments are passed as a dictionary stored in options.contextArgs where options is passed to Glsl().  e.g.

var glsl = Glsl({
    canvas: canvas,
    contextArgs: {
        preserveDrawingBuffer: true
    },
    fragment: fragmentShader,
    ...,
});

### CODE REVIEW

**Comment by gre** [comment]
Seems good to me!
I didn't know about this getContext second parameter, interesting, I'm
checking out the spec.

Can you confirm that it still work without giving the contextArgs param, I
mean that giving undefined to getContext second argument is fine for all
current implementation (can't find the answer in the spec).
It's probably OK anyway.

**Comment by k4b7** [comment]
Not specifying the second parameter to getContext is the same as passing in 'undefined'.  Also, the examples work without modification.

**Comment by gre** [comment]
I merge the pull request. Thanks for your contribution.

**Comment by k4b7** [comment]
Thanks for merging.  I tried running Makefile because I wanted to created a minified version but I don't have jsdoc installed.  I'll install jsdoc and try again this evening.  I should probably write some jsdoc comments in the code so that the docs get updated.

**Pull request merged**
